### ISSUE TITLE
LHD schedule

### ISSUE THREAD

**Issue by shetyeshail** [tudev/tudev.github.io#39]
Adding a schedule table to the LHD page.
Can be the same as last time, you can go through the commit history and find the layout for the last one and copy the code over.

10:30am: doors open
10:45am: kickoff
11:30am: hacking starts
12pm: lunch
1pm - 6pm: devtalks
7pm: dinner
8:30pm: submissions, show & tell, and judging
9:30pm: closing ceremonies
10:30pm: Fin

**Comment by lawja** [comment]
Added, should be good to close
