### ISSUE TITLE
Navbar dropdown for "News and Events"

### ISSUE THREAD

**Issue by shetyeshail** [tudev/tudev.github.io#4]
Need to add a dropdown in the navbar for the "News and Events" button. On hover over the "News and Events" button the dropdown should open and show a link to our other events (./LHD, ./codeatnight, and OwlHacks.com).

**Comment by tehjawn** [comment]
I can play around with it later this week. Having user input for the general navigation experience would be very useful.

**Comment by lawja** [comment]
Added and fixed
